#python number guessing game
import random
print("NUMBER GUSSING GAME")
# THIS PROGRAM SHOWS HOW CORRECTLY YOU GUESS THE RANDOM
# NUMBER GENERATED BY THE COMPUTER WITHIN 5 CHANCES
def number_guessing_game():
 number = random.randint(1, 100)
 chances = 0
 print("guess any number between 1 and 100")
 while chances < 5:
     guess=int(input())
     if (guess == number):
         print("congratulation, you won!")
         break
     elif (guess <  number):
         print("the number you have given is low i.e. ",guess)
     elif (guess >  number):
         print("the number you have given is high i.e. ", guess)
     chances +=1
 if not chances < 5:
     print("\n YOU LOSE!!! The number is", number)
#this function is run one time
number_guessing_game()
# if user is interes in playing than he can play again
interest=input("\n Do you want to play again: Y/N \n")
while interest =='y' or interest=='Y':
    number_guessing_game()
    interest = input("Do you want to play again: Y/N \n")

print("THANKS FOR PLAYING!")








